<?php
 
// Firebase API Key
define('FIREBASE_API_KEY', 'AAAAJoEQkfs:APA91bFuX0RIbi3MgAQMzpPjuJM2GXRVnmfxwrzxttFJCNNCjpgs0MlGjOzQhpOPJt7RpRN_BzJqOZpk_I4yoOnWwH5_HGZH3Hz7AqFB6pArNhR_2EBGZXS8divqAk2fy_1BMEMKEbMC');
